import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/providers/openai.ts",
    "src/providers/anthropic.ts",
    "src/providers/gemini.ts",
    "src/providers/openrouter.ts",
    "src/providers/bedrock.ts",
    "src/providers/vertex.ts",
    "src/providers/ollama.ts",
    "src/mcp/index.ts",
    "src/lsp/index.ts",
    "src/server/index.ts",
    "src/client/index.ts",
    "src/acp/index.ts",
    "src/a2a/index.ts",
    "src/jsonrpc/index.ts",
    "src/cli/index.ts",
    "src/docker.ts",
    "src/e2b.ts",
    "src/freestyle.ts",
    "src/ssh.ts",
    "src/sprites.ts",
  ],
  format: ["esm"],
  dts: true,
  sourcemap: true,
  clean: true,
  target: "node18",
  outDir: "dist",
});
